version: '3.7'
services:

  postal-app:
    image: siebsie23/docker-postal:latest
    container_name: postal-app
    ports:
      - "25:25"
    labels:
      - traefik.docker.network=traefik-public
      - traefik.http.routers.postal.rule=Host(`postal.example.com`)
      - traefik.http.routers.postal.entrypoints=websecure
      - traefik.http.routers.postal.tls=true
      - traefik.http.routers.postal.tls.certresolver=leresolver
      - traefik.http.services.postal-app.loadbalancer.server.port=5000
    volumes:
      - ./logs/postal:/logs
      - ./config/postal:/config
      - /root/traefik/certs:/certs
    environment:
      - CONTAINER_NAME=postal-app
      - CONTAINER_ENABLE_MONITORING=false

      - DB_HOST=postal-db
      - DB_PORT=3306
      - DB_NAME=postal
      - DB_USER=postal
      - DB_PASS=postalpass

    ## A great idea is to delete this block after first install.
      - DB_ROOT_PASS=rootpassword
      - ADMIN_EMAIL=example@hostname.com
      - ADMIN_PASS=password
      - ADMIN_FNAME=Example
      - ADMIN_LNAME=Admin
    ##

      - RABBITMQ_HOST=postal-rabbitmq
      - RABBITMQ_USER=postal
      - RABBITMQ_PASS=password
      - RABBITMQ_VHOST=/postal

      - ENABLE_SPAMASSASSIN=true
      - SPAMASSASSIN_HOST=postal-spamassassin

      - ENABLE_CLAMAV=true
      - CLAMAV_HOST=postal-clamav

      - DNS_HOSTNAME=postal.example.com
      - DNS_MX=postal.example.com
      - DNS_RETURN_PATH=rp.postal.example.com
      - DNS_ROUTE_DOMAIN=routes.postal.example.com
      - DNS_TRACK_DOMAIN=postal.example.com
      - DNS_SPF=spf.postal.example.com
      - DNS_DKIM_IDENTIFIER=postal
      - DNS_DOMAIN_VERIFY_PREFIX=kd-verify

      - SMTP_SERVER_ENABLE_TLS=true
      - SMTP_SERVER_TLS_CERT=/certs/certs/postal.example.com.crt
      - SMTP_SERVER_TLS_KEY=/certs/private/postal.example.com.key

      - SMTP_FROM_ADDRESS=noreply@example.com
      - SMTP_FROM_NAME=Postal
      - SMTP_HOST=127.0.0.1
      - SMTP_USER=   ## Fill these in after you have a working installation and server to be able to invite users
      - SMTP_PASS=   ##

      - WEB_HOST=postal.example.com
      - WEB_PROTOCOL=https

    networks:
      - traefik-public
      - services
    restart: always

  postal-db:
    image: tiredofit/mariadb:10.11
    container_name: postal-db
    volumes:
      - ./dbbackup:/backup
      - ./db:/var/lib/mysql
      - ./config/mariadb:/etc/mysql/conf.d
    environment:
      - DB_CONFIGURATION=default
      - ROOT_PASS=postalrpass
      - DB_NAME=postal
      - DB_USER=postal
      - DB_PASS=postalpass
      - DB_BACKUP=true
      - DB_BACKUP_NAME=postal
      - DB_BACKUP_USER=postal
      - DB_BACKUP_PASS=postalpass
      - DB_BACKUP_CLEANUP_TIME=10080
      - CONTAINER_NAME=postal-db
      - CONTAINER_ENABLE_MONITORING=false
    networks:
      - services
    restart: always

  postal-rabbitmq:
    container_name: postal-rabbitmq
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/postal
      - CONTAINER_NAME=postal-rabbitmq
    networks:
      - services
    restart: always

  postal-clamav:
    container_name: postal-clamav
    image: tiredofit/clamav
    volumes:
      - ./data/clamav:/data/
      - ./logs/clamav:/logs/
    environment:
      - CONTAINER_NAME=postal-clamav
      - CONTAINER_ENABLE_MONITORING=false
    networks:
      - services
    restart: always

  postal-spamassassin:
    image: tiredofit/spamassassin
    container_name: postal-spamassassin
    volumes:
      - ./logs/spamassassin:/logs/
      - ./data/spamassassin/conf:/config/
      - ./data/spamassassin/data:/data/
    environment:
      - CONTAINER_NAME=postal-spamassassin
      - CONTAINER_ENABLE_MONITORING=false
    networks:
      - services
    restart: always

networks:
  traefik-public:
    external: true
  services:
    driver: bridge
